/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createUserSchema {
  email: string;
  name: string;
  password: string;
  role: 'admin' | 'member';
}

export interface updateUserSchema {
  id: number;
  name: string;
  role: 'admin' | 'member';
  updated_at?: Date;
}
